name: teste
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.3.0 # ou a versão mais recente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/enemy1.png
    - assets/images/player.png
    - assets/images/pink_projectile.png
    - assets/images/magic_corte_magico.png
    - assets/images/magic_fogo1.png
    - assets/images/magic_gravitacional.png
    - assets/images/magic_queda_raio.png
    - assets/images/magic_tornado.png
    - assets/images/magic_raio_eletrico.png
    - assets/images/icon_fogo_habilidade.png
    - assets/images/icon_rasgo_magico.png
    - assets/images/icon_gravitacional.png
    - assets/images/icon_raio_eletrico.png
    - assets/images/icon_tornado.png
    - assets/images/icon_queda_raio.png
    - assets/images/tile.png
    - assets/images/inimigo1.png
